export const orderDetail = 
  [{
    orderedByEmail: 'jaclynwolff@aol.com',
    orderedByFirstName: 'Jaclyn',
    orderedByLastName: 'Wolff',
    orderedByPhone: '(303) 345-3888',
    order_id: 19641,
    willCallFirstName: 'Jaclyn',
    willCallLastName: 'Wolff',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '2'
  },
  {
    orderedByEmail: 'mbrom312@gmail.com',
    orderedByFirstName: 'Tobin',
    orderedByLastName: 'Bromberg',
    orderedByPhone: '(917) 968-5926',
    order_id: 19679,
    willCallFirstName: 'Tobin',
    willCallLastName: 'Bromberg',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '2'
  },
  {
    orderedByEmail: 'paza0406@colorado.edu',
    orderedByFirstName: 'Paul',
    orderedByLastName: 'Zarlingo',
    orderedByPhone: '(303) 717-1071',
    order_id: 19685,
    willCallFirstName: 'Paul',
    willCallLastName: 'Zarlingo',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '1'
  },
  {
    orderedByEmail: 'jordan.bourbo@gmail.com',
    orderedByFirstName: 'Jordan',
    orderedByLastName: 'Bourbo',
    orderedByPhone: '(706) 312-9653',
    order_id: 19557,
    willCallFirstName: 'Jordan',
    willCallLastName: 'Bourbo',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '2'
  },
  {
    orderedByEmail: 'jordan.a.hensel@gmail.com',
    orderedByFirstName: 'Jordan',
    orderedByLastName: 'Hensel',
    orderedByPhone: '(414) 617-7032',
    order_id: 19482,
    willCallFirstName: 'Jordan',
    willCallLastName: 'Hensel',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '3'
  },
  {
    orderedByEmail: 'sschloss12@gmail.com',
    orderedByFirstName: 'Scott',
    orderedByLastName: 'Schloss',
    orderedByPhone: '(513) 293-8130',
    order_id: 19639,
    willCallFirstName: 'Scott',
    willCallLastName: 'Schloss',
    firstBusLoadTime: '15:00',
    lastBusDepartureTime: '15:30',
    streetAddress: '638 East Colfax Avenue, Denver, CO 80203',
    locationName: 'Denver - Colfax/Cap Hill Cheba Hut',
    city: 'Denver',
    date: '07/03/2022',
    headliner: 'Zeds Dead',
    support1: '',
    support2: '',
    support3: '',
    venue: 'Red Rocks Amphitheatre',
    res_count: '1'
  }]